version: '3'

services:
  selenium:
    image: selenium/hub:3.8.1
    ports:
      - 4444:4444

  chrome:
    image: selenium/node-chrome:3.8.1
    depends_on:
      - selenium
    volumes:
      - /dev/shm:/dev/shm
    environment:
      - HUB_HOST=selenium
      - HUB_PORT=4444

  firefox:
    image: selenium/node-firefox:3.8.1
    depends_on:
      - selenium
    volumes:
      - /dev/shm:/dev/shm
    environment:
    - HUB_HOST=selenium
    - HUB_PORT=4444

  todoapp:
    build: app/
    ports:
      - 8080:80

  tests:
    build: .
    depends_on:
      - selenium
      - chrome
      - firefox
      - todoapp
    volumes:
    - "./error-shots:/usr/app/error-shots"
    environment:
    - SELENIUM_ENV=selenium
    - TEST_ENV=todoapp
